server:
  port: 8761

spring:
  application:
    name: service-registry

# Expose actuator endpoints for health check
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: INFO