server:
  port: 8761

eureka:
  instance:
    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: INFO