server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG