server:
  port: 8761

spring:
  application:
    name: service-registry
  profiles:
    active: default

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false  # Don't register itself with eureka
    fetchRegistry: false       # Don't fetch registry info (since it's the registry)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000
    enable-self-preservation: false   # Disable in development, enable in production

# Logging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO