server:
  port: 8082

spring:
  application:
    name: order-broker
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:configserver:http://localhost:8888/resilience4j-base.yml

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.mealbroker: DEBUG
    org.springframework.cloud.circuitbreaker.resilience4j: INFO
    io.github.resilience4j: INFO