server:
  port: 8082

spring:
  application:
    name: order-broker

  # Config server properties (optional)
  config:
    import: "optional:configserver:http://localhost:8888"

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Resilience4j Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      placeOrder:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      updateOrderStatus:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      cancelOrder:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      placeOrder:
        timeoutDuration: 10s
      updateOrderStatus:
        timeoutDuration: 4s
      cancelOrder:
        timeoutDuration: 6s

# Feign client configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.mealbroker: DEBUG
    org.springframework.cloud.circuitbreaker.resilience4j: INFO
    io.github.resilience4j: INFO