server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:servicedb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.mealbroker: DEBUG