server:
  port: 8086

spring:
  application:
    name: location-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.mealbroker: DEBUG