# Configuration for Order Broker Service

server:
  port: 8082

spring:
  application:
    name: order-broker

  # Kafka configuration for event publishing
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # Resilience4j Circuit Breaker configuration
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
  timelimiter:
    instances:
      default:
        timeoutDuration: 4s

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logging configuration
logging:
  level:
    com.mealbroker: INFO
    org.springframework.cloud.circuitbreaker: INFO
    io.github.resilience4j: INFO