server:
  port: 8086

spring:
  application:
    name: location-service

  # Config server properties (optional)
  config:
    import: "optional:configserver:http://localhost:8888"

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logging
logging:
  level:
    root: INFO
    com.mealbroker: DEBUG