server:
  port: 8086

spring:
  application:
    name: location-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.mealbroker: DEBUG